/*Criando Tabela de identificação classes produtos*/
CREATE TABLE core.classe_produto (
	id_classe SERIAL PRIMARY KEY,
	classe_produto VARCHAR(30),
	ativo BOOLEAN NOT NULL DEFAULT TRUE
);

/*Criando Tabela de tipos Produto(campanha, linha, descontinuado)*/
CREATE TABLE core.tipo_produto (
	id_tipo_produto SERIAL PRIMARY KEY,
	tipo_produto VARCHAR(30) NOT NULL UNIQUE,
	produto_controla_estoque BOOLEAN NOT NULL DEFAULT TRUE
);

/*Criando Tabela de movimentação estoque( Entrada, Saida, Venda, Avaria, ETC)*/
CREATE TABLE core.tipo_movimentacao_estoque (
	id_tipo_movimentacao SERIAL PRIMARY KEY,
	tipo_movimentacao VARCHAR(30) NOT NULL UNIQUE
);

/*Criando Tabela documento Entrada, que mostra as notas de entrada*/
CREATE TABLE core.documento_entrada (
	id_documento_entrada SERIAL PRIMARY KEY,
	numero_nota INT NOT NULL, 
	data_emissao DATE NOT NULL
);

/*Criando Tabela  de auditoria, que da mais detalhes sobre a auditoria*/
CREATE TABLE core.auditoria_estoque (
	id_auditoria SERIAL PRIMARY KEY, 
	data_auditoria TIMESTAMP NOT NULL,
	observacoes TEXT
);

/*Criando Tabela produto*/
CREATE TABLE core.produto (
	codigo_produto INT PRIMARY KEY,
	id_classe INT NOT NULL,
	nome_produto VARCHAR(100),
	id_tipo_produto INT NOT NULL,
	status_cadastro VARCHAR(20) NOT NULL DEFAULT 'VALIDADO';

	CONSTRAINT fk_produto_classe
		FOREIGN KEY  (id_classe)
		REFERENCES core.classe_produto,

	CONSTRAINT fk_produto_tipo
		FOREIGN KEY  (id_tipo_produto)
		REFERENCES core.tipo_produto,

	CONSTRAINT chk_status_cadastro
		CHECK (status_cadastro IN ('PENDENTE', 'VALIDADO'));

);

/*Criando Tabela preço_produto*/
CREATE TABLE core.historico_preco_produto (
	id_preco_produto  SERIAL PRIMARY KEY,
	codigo_produto INT NOT NULL,
	preco_produto NUMERIC(10,2),
	data_registro TIMESTAMP NOT NULL,

	CONSTRAINT fk_produto_codigo
		FOREIGN KEY  (codigo_produto)
		REFERENCES core.produto (codigo_produto),

	CONSTRAINT uk_produto_data_preco
    	UNIQUE (codigo_produto, data_registro)
);

/*Criando Tabela preço_produto*/
CREATE TABLE core.venda (
	id_venda  SERIAL PRIMARY KEY,
	numero_nota VARCHAR(100),
	data_venda TIMESTAMP  NOT NULL,
	valor_total NUMERIC(10,2) NOT NULL,
	valor_imposto NUMERIC(10,2) NOT NULL,
	id_forma_pagamento INT NOT NULL,

	CONSTRAINT uk_venda_numero_nota
        UNIQUE (numero_nota),

	CONSTRAINT fk_venda_forma_pagamento
		FOREIGN KEY (id_forma_pagamento)
		REFERENCES core.forma_pagamento(id_forma_pagamento)

);

/*Criando Tabela Item_venda*/
CREATE TABLE core.item_venda (
    id_item_venda INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda INT NOT NULL,
    codigo_produto INT NOT NULL,
    numero_linha INT NOT NULL,
    quantidade INT NOT NULL,
    preco_unitario_vendido NUMERIC(10,2) NOT NULL,

    CONSTRAINT fk_item_venda_venda
        FOREIGN KEY (id_venda)
        REFERENCES core.venda (id_venda),

    CONSTRAINT fk_item_venda_produto
        FOREIGN KEY (codigo_produto)
        REFERENCES core.produto (codigo_produto),

    CONSTRAINT uk_venda_linha
        UNIQUE (id_venda, numero_linha)
);
CREATE INDEX idx_item_venda_id_venda
ON core.item_venda (id_venda);

/*Criando Tabela Item_auditoria estoque*/
CREATE TABLE core.item_auditoria_estoque (
    id_item_auditoria_estoque INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_auditoria INT NOT NULL,
    codigo_produto INT NOT NULL,
    quantidade_sistema INT NOT NULL,
    quantidade_contada INT NOT NULL,

    diferenca INT GENERATED ALWAYS AS (quantidade_contada - quantidade_sistema) STORED,


	CONSTRAINT fk_auditoria
        FOREIGN KEY (id_auditoria)
        REFERENCES core.auditoria_estoque (id_auditoria),

	CONSTRAINT fk_item_venda_produto
        FOREIGN KEY (codigo_produto)
        REFERENCES core.produto (codigo_produto),

	CONSTRAINT uk_auditoria_produto
        UNIQUE (id_auditoria, codigo_produto)

);

/*Criando Tabela movimento estoque*/
CREATE TABLE core.movimento_estoque (
    id_movimentacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_produto INT NOT NULL,
    quantidade INT NOT NULL,
    data_movimentacao TIMESTAMP NOT NULL,
    id_tipo_movimentacao INT NOT NULL,
    id_item_entrada INT,

    CONSTRAINT fk_movimento_produto
        FOREIGN KEY (codigo_produto)
        REFERENCES core.produto (codigo_produto),

    CONSTRAINT fk_movimento_item_entrada
        FOREIGN KEY (id_item_entrada)
        REFERENCES core.item_entrada (id_item_entrada),

    CONSTRAINT fk_tipo_movimentacao
        FOREIGN KEY (id_tipo_movimentacao)
        REFERENCES core.tipo_movimentacao_estoque(id_tipo_movimentacao),

    CONSTRAINT ck_quantidade_positiva
        CHECK (quantidade > 0)
);

CREATE INDEX idx_movimento_data_produto
ON core.movimento_estoque (data_movimentacao, codigo_produto);

/*CRIANDO TABELA DE FORMA DE PAGAMENTOS*/
CREATE TABLE core.forma_pagamento (
    id_forma_pagamento SERIAL PRIMARY KEY,
    descricao VARCHAR(30) NOT NULL UNIQUE
);

/*Criando Tabela Item Entrad*/
CREATE TABLE core.item_entrada(
	id_item_entrada INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	codigo_produto INT NOT NULL,
	id_documento_entrada INT NOT NULL,
	quantidade INT NOT NULL, 
	valor_produto NUMERIC(10,2) NOT NULL,
	lote VARCHAR(20),
	data_fabricacao DATE,
	data_vencimento DATE, 
	icms NUMERIC(10,2),
	ipi NUMERIC(10,2),
	pis NUMERIC(10,2),
	cofins NUMERIC(10,2),
	custo_total_item NUMERIC(14,2) NOT NULL,
    

	CONSTRAINT fk_codigo_produto
        FOREIGN KEY (codigo_produto)
        REFERENCES core.produto (codigo_produto),

	CONSTRAINT fk_documento_entrada
        FOREIGN KEY (id_documento_entrada)
        REFERENCES core.documento_entrada (id_documento_entrada),

	CONSTRAINT ck_quantidade_positiva
        CHECK (quantidade > 0)

)




